version: "3.8"
services:
  test_p${port}_job:
    container_name: test_p${port}_job
    image: test_p${port}_job_img
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /root/projects/test:/app/output

