services:
  test_job_data_th_3_10:
    container_name: test_job_data_th_3_10
    image: test_job_data_th_img
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.data_th
    volumes:
      - /root/projects/test:/app/output

networks:
  default:
    external: true
    name: reverse-proxy


